#!/usr/bin/env bash

DELIMITER="_"

FNAME=${1:-new}
EDITOR="${EDITOR:-/usr/bin/env vim}"

file=$(ls -1 | grep -E "^([0-9]{1,6}${DELIMITER})?${FNAME}\$") \
&& set -- "$file" "${@:2}" \
&& exec ${EDITOR} ${@}

i=00
for f in *; do
  if [[ $f =~ ^([0-9]{1,6})${DELIMITER}.+$ ]]; then
    j=${BASH_REMATCH[1]}
    test ${j#0} -gt ${i#0} && i=$j
  fi
done

pad="${#i}"
next_i=$(( ${i#0} + 1 ))
next_i_str=$(printf "%0${pad}d" "${next_i}")

exec ${EDITOR} ${next_i_str}${DELIMITER}${@}
